version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
    groups:
      dev-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch
      prod-dependencies:
        dependency-type: production
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - github-actions
    groups:
      actions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
