repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--indent=2"
          - "--no-sort-keys"
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: npm run lint
        language: system
        types_or: [javascript, jsx, ts, tsx]
        pass_filenames: false
      - id: jest
        name: jest
        entry: npm test
        language: system
        files: \.(js|jsx|ts|tsx|json)$
        pass_filenames: false
